import {
  ChangeEventHandler,
  MouseEventHandler,
  useContext,
  useEffect,
  useState,
} from "react";
import "../node_modules/xterm/css/xterm.css";

import "./form.css";
import { SpawnerFormContext } from "./state";
import { ProfileOptions } from "./ProfileOptions";
import useFormCache from "./hooks/useFormCache";
import { PermalinkContext } from "./context/Permalink";
import Permalink from "./components/Permalink";
import { IProfileOptions } from "./types/config";

/**
 * Walks the profile_options tree to collect kubespawner_override values from
 * nested choices (depth > 0). KubeSpawner already handles depth-0 choices.
 */
function collectNestedOverrides(
  profileOptions: IProfileOptions,
  fieldPrefix: string,
  form: HTMLFormElement,
  depth = 0,
): Record<string, string> {
  const overrides: Record<string, string> = {};
  for (const [optionKey, option] of Object.entries(profileOptions)) {
    const fieldName = `${fieldPrefix}--${optionKey}`;
    const input = form.querySelector<HTMLInputElement>(`[name="${fieldName}"]`);
    if (!input?.value) continue;
    const choice = option.choices?.[input.value];
    if (!choice) continue;
    if (depth > 0 && choice.kubespawner_override) {
      Object.assign(overrides, choice.kubespawner_override);
    }
    if (choice.profile_options) {
      Object.assign(
        overrides,
        collectNestedOverrides(
          choice.profile_options,
          `${fieldName}--${input.value}`,
          form,
          depth + 1,
        ),
      );
    }
  }
  return overrides;
}

/**
 * Generates the *contents* of the form shown in the profile selection page
 *
 * A <form> tag is generated by JupyterHub, and we don't have control over it. A <submit>
 * is also generated, but we hide it with CSS and use our own so we have better control over
 * validation.
 */
function Form() {
  const {
    profile: selectedProfile,
    setProfile,
    profileList
  } = useContext(SpawnerFormContext);
  const { permalinkValues, setPermalinkValue, permalinkParseError } = useContext(PermalinkContext);
  const [profileError, setProfileError] = useState("");
  const [formErrors, setFormErrors] = useState<Element[]>([]);
  const {
    cacheChoiceOption,
    cacheRepositorySelection,
    buildImageStart,
    isBuildingImage,
    isDynamicBuildActive,
  } = useFormCache();


  const collectFormErrors = (form: HTMLFormElement) => {
    setTimeout(() => {
      const errors = form.getElementsByClassName("invalid-feedback");
      setFormErrors(Array.from(errors));
    }, 10);
    setTimeout(() => {
      window.scrollTo(0, document.body.scrollHeight);
    }, 100);
  };

  const cacheFormValues = (form: HTMLFormElement) => {
    const cacheUnlistedChoices = form.getElementsByClassName("cache-unlisted-choice");
    Array.from(cacheUnlistedChoices).forEach((el) => {
      const { id, value } = el as HTMLInputElement;
      cacheChoiceOption(id, value);
    });

    const cacheRepositories = form.getElementsByClassName("cache-repository");
    Array.from(cacheRepositories).forEach((el) => {
      const { id, value } = el as HTMLInputElement;
      if (id.endsWith("--repo")) {
        const fieldName = id.slice(0, -6);
        const refField = form.querySelector(`#${CSS.escape(`${fieldName}--ref`)}`);
        if (refField) {
          cacheRepositorySelection(fieldName, value, (refField as HTMLInputElement).value);
        }
      }
    });
  };

  const preBuildValidate = (form: HTMLFormElement): boolean => {
    let firstInvalid: HTMLInputElement | null = null;
    form.querySelectorAll<HTMLInputElement>("input, select, textarea").forEach((field) => {
      // Hidden text input for dynamically buit image name (input is empty)
      if (field.dataset.dynamicBuild === "true") return;
      if (field.disabled) return;
      if (!field.checkValidity()) {
        if (!firstInvalid) firstInvalid = field;
      }
    });
    if (firstInvalid) {
      firstInvalid!.reportValidity();
      return false;
    }
    return true;
  };

  const submitFlow = async (
    form: HTMLFormElement | null,
    nativeEvent?: { preventDefault: () => void },
  ): Promise<boolean> => {
    setProfileError("");
    setFormErrors([]);
    // When there is no selected profile
    if (!selectedProfile) {
      nativeEvent?.preventDefault();
      setProfileError("Select a container profile");
      return false;
    }
    // when dynamic image build is requested
    if (isDynamicBuildActive && buildImageStart) {
      if (!form) return false;
      nativeEvent?.preventDefault();
      // but there is an error in form
      if (!preBuildValidate(form)) {
        collectFormErrors(form);
        return false;
      }

      try {
        await buildImageStart();
      } catch {
        collectFormErrors(form);
        return false;
      }

      cacheFormValues(form);
      form.requestSubmit();
      return true;
    }

    if (form && !form.checkValidity()) {
      nativeEvent?.preventDefault();
      collectFormErrors(form);
      return false;
    }

    if (form) {
      cacheFormValues(form);
    }
    // When submit happened by mimicking the button (from query parameter)
    if (!nativeEvent) {
      form?.requestSubmit();
    }
    return true;
  };

  const handleSubmit: MouseEventHandler<HTMLButtonElement> = (e) => {
    const button = e.currentTarget;
    const form = button.closest("form");

    void submitFlow(form, e);
  };

  const handleProfileSelect: ChangeEventHandler<HTMLInputElement> = (e) => {
    const slug = e.target.value;
    setProfile(slug);
    setPermalinkValue("profile", slug);
    setProfileError("");
  };

  useEffect(() => {
    // scroll the selected profile into view
    if (permalinkValues.profile) {
      const targetElement = document.getElementById(`profile-${permalinkValues.profile}`);
      const observer = new IntersectionObserver((e) => {
        if (e.length > 0 && !e[0].isIntersecting) {
          // scroll the element into if not fully visible
          targetElement.scrollIntoView();
        }
        // Disconnecting the oberserver, we only want to scroll once
        observer.disconnect();
      }, {
        root: null,
        rootMargin: "0px",
        threshold: 1, // we want the element to be fully visible
      });
      observer.observe(targetElement);
    }
  }, [permalinkValues.profile]);

  // @TODO: Replace setTimeout (hack for racing condition) + dispatchEvent (hack for stale closure)
  // to proper sequencing of the events and calling submitflow directly
  useEffect(() => {
    if (permalinkValues["autoStart"] === "true") {
      const form = document.querySelector("form");
      if (form) {
        const button = form.querySelector("button[type=\"submit\"]") as HTMLButtonElement | null;
        if (button) {
          setTimeout(() => {
            button.dispatchEvent(new window.MouseEvent("click", { bubbles: true, cancelable: true }));
          }, 1000); // Give the form a second to render, and the profile to be selected, HACK but it works
        }
      }
    }
  }, [permalinkValues]);

  return (
    <fieldset
      aria-label="Select profile"
      aria-description="First, select the profile; second, configure the options for the selected profile."
    >
      {permalinkParseError && <div className="alert alert-warning">Unable to parse permalink configuration.</div>}
      <input
        type="radio"
        className="hidden"
        name="profile"
        value={selectedProfile?.slug}
        checked
        readOnly
      />
      {profileList.map((profile) => {
        const { display_name, description, profile_options, slug } = profile;

        return (
          <div
            id={`profile-${slug}`}
            key={slug}
            className={`profile-select ${selectedProfile?.slug === slug ? "selected-profile" : ""
            }`}
            onClick={() => {
              setProfile(slug);
              setPermalinkValue("profile", slug);
            }}
          >
            {profileList.length > 1 && (
              <input
                type="radio"
                name="select-profile"
                id={`profile-option-${slug}`}
                value={slug}
                onChange={handleProfileSelect}
                required
                checked={selectedProfile?.slug === slug}
                aria-labelledby={`profile-option-${slug}-label`}
              />
            )}
            <div className="profile-select-body">
              <div className="d-flex align-items-start">
                <div
                  id={`profile-option-${slug}-label`}
                  className="profile-select-label flex-grow-1"
                >
                  <h2>{display_name}</h2>
                  <p>{description}</p>
                </div>
                {selectedProfile?.slug === slug && <Permalink />}
              </div>

              {profile_options && (
                <ProfileOptions profile={slug} config={profile_options} />
              )}
            </div>
          </div>
        );
      })}

      {(formErrors.length > 0 || profileError) && (
        <div
          className={`form-errors ${formErrors.length > 0 || profileError ? "d-block" : "d-none"}`}
        >
          <p><b>Unable to start the server. Check the error below.</b></p>
          <ul>
            {profileError && <li>{profileError}</li>}
            {formErrors.map((err, index) => (
              // eslint-disable-next-line react/no-array-index-key
              <li key={index}>
                <a
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    err.parentElement.scrollIntoView();
                  }}
                >
                  {err.textContent}
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}

      <button
        className="btn btn-jupyter form-control"
        type="submit"
        onClick={handleSubmit}
        disabled={isBuildingImage}
      >
        {isDynamicBuildActive ? "Build Image and Start" : "Start"}
      </button>
    </fieldset>
  );
}

export default Form;
